# Generated by Django 2.2.1 on 2019-09-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwname', models.CharField(max_length=200)),
                ('madeby', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('duedate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=50)),
                ('professor_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Homework_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default='Wating', max_length=200)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Student')),
            ],
        ),
    ]
