# Generated by Django 2.2.3 on 2019-09-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_homework_student_homework_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom_student',
        ),
        migrations.RemoveField(
            model_name='homeworks',
            name='classroom',
        ),
        migrations.DeleteModel(
            name='Classrooms',
        ),
    ]
