# Generated by Django 2.2.3 on 2019-09-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190917_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(default=0),
        ),
    ]
