# Generated by Django 2.2.1 on 2019-09-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190911_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_student',
            name='score',
            field=models.CharField(default='Waiting', max_length=200),
        ),
    ]
