# Generated by Django 2.2.3 on 2019-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='refer',
            field=models.IntegerField(default=0),
        ),
    ]
